def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

# Dynamically toggle modular headers based on environment variable
if ENV['ENABLE_FLIPPER'] == "1"
  Pod::UI.puts "Flipper is enabled".green
  flipper_config = FlipperConfiguration.enabled
else
  Pod::UI.puts "Flipper is disabled".yellow
  flipper_config = FlipperConfiguration.disabled
  use_modular_headers!
end

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'LocationAccuracy',
  'LocationWhenInUse',
  'Camera',
  'PhotoLibrary',
  'PhotoLibraryAdditions',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

$RNFirebaseAnalyticsWithoutAdIdSupport = true

target 'GaloyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :flipper_configuration => flipper_config, # Ensure this is passed correctly
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          if target.name === "RNReanimated"
            config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          end
        end
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
